apiVersion: v1
kind: Pod
metadata:
  name: docker-cwl-pod
  labels:
    task-type: sbg-task
spec:
  restartPolicy: Never
  serviceAccountName: airflow-worker

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: task-type
                operator: In
                values:
                  - sbg-task
          topologyKey: kubernetes.io/hostname

  containers:
  - name: cwl-docker
    image: ghcr.io/unity-sds/unity-sps/sps-docker-cwl:2.2.0
    imagePullPolicy: Always
    command: ["/usr/share/cwl/docker_cwl_entrypoint.sh"]
    securityContext:
      privileged: true
    resources:
      requests:
        ephemeral-storage: "20Gi"
      limits:
        ephemeral-storage: "20Gi"
