name: Setup Action
description: Setups Python and dependencies for executing tests
runs:
  using: 'composite'

  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      id: install-dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        pip install git+https://github.com/unity-sds/unity-monorepo.git@main#subdirectory=libs/unity-py
        pip freeze
      shell: bash
